### ISSUE TITLE
how can i compile this file on mac os?

### ISSUE THREAD

**Issue by khanhvuNOIS** [diamondbybold/ejabberd_mod_offline_post#1]
Can u give me beam file ?

**Comment by joaoffm** [comment]
- clone ejabberd source
- put the .erl file on src/ dir
- follow instructions ( https://github.com/processone/ejabberd ) for compiling

worked on Ubuntu 14.04 with necessary dependencies installed

Use a virtual machine / vagrant for installing linux/ubuntu on osx

**Comment by khanhvu161188** [comment]
Tks so much. I've compiled it success. And now i will test it with server here

**Comment by khanhvu161188** [comment]
@joaoffm  you can close this issue now

**Comment by joaoffm** [comment]
No problem ;)
